### ISSUE TITLE
Bring in updates/fixes made to A-Frame's cursor

### ISSUE THREAD

**Issue by bryik** [bryik/aframe-controller-cursor-component#1]
e.g.
- [Ignore cursor's own element in intersections](https://github.com/aframevr/aframe/pull/1936)
- [Cursor events don't fire correctly when multiple objects intersect the path](https://github.com/aframevr/aframe/issues/1882)

**Comment by ngokevin** [comment]
I think https://github.com/bryik/aframe-vive-cursor-component/pull/8 fixes
