### ISSUE TITLE
some issues with hand-controls and oculus-touch-controls

### ISSUE THREAD

**Issue by giordyb** [bryik/aframe-controller-cursor-component#10]
I'm not sure if it's an issue with your component or with aframe 0.5.0 in general but I'm adding this issue here since it affects your component:

- both hand-controls and oculus-touch-controls require the raycaster to be set.
to get the basic example to work I had to add  
`raycaster="objects: #sphere"` to the entity

- hand-controls: when I click the sphere the "click" event gets called twice instead of once. this does not happen with the oculus-touch-controls.

**Comment by rxl881** [comment]
I'm also seeing the same problem with the raycaster needing to be set when using vive controllers. giordyb's workaround of adding the raycaster explicitly on the entity worked for me.

**Comment by pinnareet** [comment]
I'm not sure, but I think it may be a bug with aframe raycaster implementation where they check for objects being null to intersect with everything, but actually pass an empty string {''} as the default.

**Comment by bryik** [comment]
With hand-controls, I didn't need to add the raycaster explicitly but the "click" event was called twice instead of once. Considering it doesn't happen with vive-controls, I'm not sure the problem is with controller-cursor.

**Comment by ngokevin** [comment]
It's a bug with A-Frame https://github.com/aframevr/aframe/issues/2379
