### ISSUE TITLE
"Not found" error when using the URL supplied in readme.

### ISSUE THREAD

**Issue by caseyyee** [bryik/aframe-controller-cursor-component#14]
When using:

```html
<script src="https://unpkg.com/aframe-controller-cursor-component/dist/aframe-controller-component.min.js"></script>
```

I get:
`
Not found: file "/dist/aframe-controller-component.min.js" in package aframe-controller-cursor-component@0.2.6
`

**Comment by bryik** [comment]
The URL is supposed to be `https://unpkg.com/aframe-controller-cursor-component@0.2.6/dist/aframe-controller-cursor-component.min.js`. The "cursor" part is missing from the URL in the readme, I'll update the link. 

Thanks for reporting!
