### ISSUE TITLE
TypeError: attributes.position is undefined

### ISSUE THREAD

**Issue by bryik** [bryik/aframe-controller-cursor-component#16]
**Problem:** Controller cursor is broken, not sure what changed. Reported by samvr on Slack.

**System:** Desktop/Vive/Firefox Nightly

**Example:** https://bryik.github.io/aframe-controller-cursor-component/basic/

**Console dump:**

![image](https://cloud.githubusercontent.com/assets/12419712/26365763/8efa68d4-3fb6-11e7-9baa-b26825e85d7f.png)

**Comment by bryik** [comment]
In Chromium, no error occurs but the Vive controller models don't appear.

**Comment by bryik** [comment]
Possibly a return of issues #2 and/or #4?

**Comment by bryik** [comment]
Probably a race condition. The raycaster tries to compute an intersection on a geometry that has not yet been fully created (so its position attribute is undefined). Adding `controller-cursor` to the vive-controls entity after the scene has loaded (using dev-tools) avoids the error.

Forcing controller-cursor to wait for the scene to load might fix this problem. Alternatively, perhaps A-Frame's raycaster code could be altered?

**Comment by ngokevin** [comment]
I get this too, I think it's a regression. I'll check it out now.

**Comment by ngokevin** [comment]
I think this may be because obj-model sets `material` as a dependency which will create an empty buffer geometry.

**Comment by bryik** [comment]
This has been [fixed on A-Frame master](https://github.com/aframevr/aframe/pull/2696); see [this CodePen](https://codepen.io/bryik/pen/MmLwpQ) for working example.

In the short-term, use A-Frame master.
