### ISSUE TITLE
crashes scene

### ISSUE THREAD

**Issue by sirkitree** [bryik/aframe-controller-cursor-component#2]
Hi there,

I'm trying to use this component in a scene but each time I add the `vive-cursor` attribute, it crashes the scene.

I'm using the latest master aframe and the latest of this component as well. Here's a codepen to see what's happening: http://codepen.io/sirkitree/pen/aBqQab?editors=1000 - if you modify that scene by just adding the `vive-cursor` attribute to the vive-control entity, you'll see it crash.

You can't see the error on codepen's console, but here is what I get locally: 
![tugboat vr - chromium 2016-12-04 08 47 49](https://cloud.githubusercontent.com/assets/28543/20867299/5bce437e-b9fe-11e6-8778-1a0114598703.png)

Any thoughts on what I might try to get to the bottom of this?

**Comment by bryik** [comment]
My guess is that a change (probably with the raycaster) has broken vive-cursor in the latest A-Frame master build.

Curiously, adding A-Frame's own raycaster component to the vive-control entity causes the same crash, so the problem may not lie entirely with vive-cursor.

**Comment by bryik** [comment]
I believe this issue was fixed with the release of A-Frame 0.4.0.

Applying the vive-cursor component to a vive-control entity no longer causes a crash in your CodePen (I just tried it now).

**Comment by noerw** [comment]
It has a different issue with aframe 0.4.0, saying
```
TypeError: attributes.position is undefined
```
could this be related to https://github.com/aframevr/aframe/pull/1925, which was merged for 0.4.0 ?

**Comment by bryik** [comment]
@noerw Could you file a new issue with more info? I'm not sure how to reproduce that error.

**Comment by noerw** [comment]
this only occured with [this](https://rawgit.com/chenzlabs/aframe/5feeec6f625013e3381a397ea0433efb0b4c4352/dist/aframe-master.js) aframe build.
current aframe master works again, nevermind!
