### ISSUE TITLE
rename the component a more generic way

### ISSUE THREAD

**Issue by giordyb** [bryik/aframe-controller-cursor-component#3]
This is just a suggestion, but since the component works also with other types of controllers (I tested it with Oculus Touch) it would make more sense to rename it to something more generic.

**Comment by bryik** [comment]
A problem is that since I don't own a Rift, I can't test that the component works. However, I will consider renaming.

Any suggestions for a new name? "Motion control cursor" maybe?

**Comment by giordyb** [comment]
How about "tracked-controls cursor"? Both vive controllers and oculus touch wrap the "[tracked-controls component](https://aframe.io/docs/0.4.0/components/tracked-controls.html)"

**Comment by bryik** [comment]
I like that name.

How is the laser position on the Touch controller? Not too awkward, I hope?

**Comment by ngokevin** [comment]
https://github.com/bryik/aframe-vive-cursor-component/pull/8
