### ISSUE TITLE
cursor events don't match aframe cursor component

### ISSUE THREAD

**Issue by noerw** [bryik/aframe-controller-cursor-component#5]
As this component basically duplicates aframe's internal [`cursor` component](https://github.com/aframevr/aframe/blob/master/src/components/cursor.js) (both in terms of functionality and code), it should emit the same events, and more importantly, the same event-payloads.

aframe's cursor event payload changed in 0.4.0 through [this commit](https://github.com/aframevr/aframe/commit/d5f88f46477f68d2a82642b047ec827816c2ae7c), adding the `intersection` attribute, which contains important data such as the position of intersection.

I adapted this change to the `vive-cursor` component [here](https://github.com/crend02/GeoVR/blob/master/src/vive-cursor.js) and can send a PR. (this introduces no breaking changes).

In the long run, one should think about a way to avoid the code duplication, and somehow inherit the cursor components behaviour.

**Comment by bryik** [comment]
I agree. It would be nice to have all the cursors (gaze, mouse, and tracked controller) together in one place with some kind of inheritance setup--though, Mayognaise's [mouse cursor](https://github.com/mayognaise/aframe-mouse-cursor-component) is a bit different from the rest. Might be worth filing a request in A-Frame's core repo or asking about this on Slack.

Also, a PR would be well appreciated!

**Comment by noerw** [comment]
> Might be worth filing a request in A-Frame's core repo or asking about this on Slack.

will do when i find the time
